# Generated by Django 2.2.1 on 2019-05-10 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('team', models.CharField(choices=[('DOA', 'DOA'), ('GRY', 'GRY'), ('GHO', 'GHO'), ('RIP', 'RIP'), ('BOB', 'BOB'), ('BOB', 'GNX'), ('EAD', 'EAD'), ('VN1', 'VN1'), ('UTO', 'UTO'), (' ', ' ')], default=None, max_length=3)),
                ('rank', models.IntegerField(choices=[(8, 'ARCHDUKE'), (7, 'DUKE'), (6, 'EARL'), (5, 'VISCOUNT'), (4, 'BARON'), (3, 'KNIGHT')], default=3)),
            ],
        ),
        migrations.CreateModel(
            name='Subcity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coords', models.CharField(max_length=9, unique=True)),
                ('culture', models.CharField(choices=[('SA', 'ARABIA'), ('US', 'AMERICA'), ('CN', 'CHINA'), ('EU', 'EUROPE'), ('JP', 'JAPAN'), ('KR', 'KOREA'), ('RU', 'RUSSIA')], default='JP', max_length=3)),
                ('quality', models.CharField(choices=[('GLD', 'GOLD'), ('PUR', 'PURPLE'), ('BLU', 'BLUE'), ('GRN', 'GREEN')], default='BLU', max_length=6)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subCityList.Player')),
            ],
        ),
    ]
