# Generated by Django 2.2.1 on 2019-05-14 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subCityList', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcity',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='subCityList.Player'),
        ),
    ]
