# Generated by Django 2.2.1 on 2019-06-04 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subCityList', '0002_auto_20190514_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.CharField(choices=[('DOA', 'DOA'), ('GRY', 'GRY'), ('GHO', 'GHO'), ('RIP', 'RIP'), ('BOB', 'BOB'), ('BOB', 'GNX'), ('EAD', 'EAD'), ('VN1', 'VN1'), ('UTO', 'UTO'), (' ', 'TAGLESS')], default=None, max_length=3),
        ),
    ]
