# Generated by Django 2.2.1 on 2019-06-04 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subCityList', '0004_auto_20190603_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcity',
            name='culture',
            field=models.CharField(choices=[('ARABIA', 'ARABIA'), ('AMERICA', 'AMERICA'), ('CHINA', 'CHINA'), ('EUROPE', 'EUROPE'), ('JAPAN', 'JAPAN'), ('KOREA', 'KOREA'), ('RUSSIA', 'RUSSIA')], default='JAPAN', max_length=3),
        ),
        migrations.AlterField(
            model_name='subcity',
            name='quality',
            field=models.CharField(choices=[('GOLD', 'GOLD'), ('PURPLE', 'PURPLE'), ('BLUE', 'BLUE'), ('GREEN', 'GREEN')], default='BLUE', max_length=6),
        ),
    ]
