# Generated by Django 2.2.1 on 2019-06-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subCityList', '0005_auto_20190604_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcity',
            name='culture',
            field=models.CharField(choices=[('ARABIA', 'ARABIA'), ('AMERICA', 'AMERICA'), ('CHINA', 'CHINA'), ('EUROPE', 'EUROPE'), ('JAPAN', 'JAPAN'), ('KOREA', 'KOREA'), ('RUSSIA', 'RUSSIA')], default='JAPAN', max_length=7),
        ),
    ]
